# Generated by Django 4.2.7 on 2023-12-08 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_addr', models.CharField(max_length=20)),
                ('http_method', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('rev', models.IntegerField()),
                ('gid', models.IntegerField()),
                ('action', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('data_json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('src_addr', models.CharField(max_length=128)),
                ('src_port', models.IntegerField(blank=True, null=True)),
                ('dst_addr', models.CharField(max_length=128)),
                ('dst_port', models.IntegerField(blank=True, null=True)),
                ('proto', models.CharField(max_length=128)),
                ('mark_as_deleted', models.BooleanField(default=False)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.rule')),
            ],
        ),
    ]
