# Generated by Django 4.2.7 on 2023-12-18 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0001_initial'),
        ('monitor', '0002_request_endpoint_request_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.rule'),
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
