# Generated by Django 4.2.7 on 2023-12-18 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_event_rule_delete_rule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
