# Generated by Django 4.2.7 on 2023-12-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('gid', models.IntegerField()),
                ('rev', models.IntegerField()),
                ('action', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('data_json', models.JSONField()),
            ],
        ),
    ]
