# Generated by Django 4.2.7 on 2023-12-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='deprecated',
            field=models.BooleanField(default=False),
        ),
    ]
