# Generated by Django 4.2.7 on 2023-12-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0002_rule_deprecated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='data_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
